name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    name: Frontend build (Vite)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publicar artefacto (dist)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  backend:
    name: Backend install + lint + pack prod
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install deps (dev)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Syntax check entrypoint
        run: node --check src/server.js

      - name: Install deps (prod, sin dev)
        run: npm ci --omit=dev

      - name: Empaquetar backend para despliegue
        run: tar -czf ../backend-prod.tgz .

      - name: Publicar artefacto (backend-prod)
        uses: actions/upload-artifact@v4
        with:
          name: backend-prod
          path: backend-prod.tgz
