name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (Node)
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: backend } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - run: node -v && npm -v
      - name: Install deps
        run: npm ci --no-audit --no-fund || npm install --no-audit --no-fund
      - name: List files
        run: ls -la && ls -la src || true
      - name: Sanity import
        run: |
          node -e "try{require('dotenv').config();require('./src/app');console.log('backend OK')}catch(e){console.error('SANITY ERROR:',e);process.exit(1)}"

  frontend:
    name: Frontend (Vite build)
    runs-on: ubuntu-latest
    needs: backend
    defaults: { run: { working-directory: frontend } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: node -v && npm -v
      - name: Install deps
        run: npm ci --no-audit --no-fund || npm install --no-audit --no-fund
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          if-no-files-found: error
